---
- name: Install nginx on slave2
  hosts: slave2
  user: vagrant
  become: true
  become_user: root

  tasks:
  - name: install nginx
    apt:
      name: nginx
      state: latest
      update_cache: yes


